#include <algorithm>
#include <cassert>
#include <chrono>
#include <iostream>
#include <map>
#include <string>
#include <thread>
#include <vector>

struct MediaItem_Take { std::string path, label; };
struct MediaItem { double start, length; MediaItem_Take* take; };
struct MediaTrack { std::vector<MediaItem*> items; };
struct ReaProject {
  int revision;
  std::string directory, mediaDirectory;
  std::map<std::string, MediaTrack*> tracks;
};
static int sourceReads = 0, pathResolutions = 0;
static int revisionOf(ReaProject* p) { return p->revision; }
static auto GetProjectStateChangeCount_ptr = &revisionOf;
static int itemCount(MediaTrack* t) { return static_cast<int>(t->items.size()); }
static auto GetTrackNumMediaItems_ptr = &itemCount;
static MediaItem* itemAt(MediaTrack* t, int i) { return t->items.at(i); }
static auto GetTrackMediaItem_ptr = &itemAt;
static double itemValue(MediaItem* i, const char* key) {
  return std::string(key) == "D_POSITION" ? i->start : i->length;
}
static auto GetMediaItemInfo_Value_ptr = &itemValue;
static MediaItem_Take* activeTake(MediaItem* i) { return i->take; }
static auto GetActiveTake_ptr = &activeTake;
static std::string nativeTelepromptProjectFileDirectory(ReaProject* p) {
  return p ? p->directory : "";
}
static std::string nativeTelepromptProjectMediaDirectory(ReaProject* p) {
  return p ? p->mediaDirectory : "";
}
static MediaTrack* nativeFindTrackByExactName(ReaProject* p,
    const std::string& name, int* index) {
  *index = -1;
  if (!p || !p->tracks.count(name)) return nullptr;
  *index = 0;
  return p->tracks.at(name);
}
static std::string nativeReadTakeSourcePath(MediaItem_Take* t) {
  ++sourceReads;
  return t ? t->path : "";
}
static std::string nativeReadTakeText(MediaItem_Take* t) {
  return t ? t->label : "";
}
static bool nativeTelepromptLabelLooksLikeMediaPath(const std::string& s) {
  return s.find('.') != std::string::npos;
}
static std::string nativeResolveTelepromptMediaPath(const std::string& s,
    const std::string& directory, const std::string&) {
  ++pathResolutions;
  return s.empty() ? "" : directory + "/" + s;
}
static std::string nativeDetectTelepromptMediaType(const std::string& s) {
  return s.find(".mp4") != std::string::npos ? "video" : "image";
}

// Generated by run-teleprompt-scan-cache-test.js from the production source.
#include "teleprompt-scan-under-test.h"

int main() {
  MediaItem_Take video{"clip.mp4", ""}, image{"", "slide.png"};
  MediaItem first{10, 20, &video}, overlap{15, 4, &image};
  MediaTrack tp{{&first, &overlap}};
  ReaProject project{1, "A", "Media", {{"TELEPROMPT1", &tp}}};
  const auto& initial = nativeTelepromptTrackScan(&project, "TELEPROMPT1");
  assert(initial.items.size() == 2);
  assert(initial.items[0].start == 10 && initial.items[0].end == 30);
  assert(initial.items[0].priority == 2 && initial.items[1].priority == 1);
  assert(initial.items[1].mediaPath == "A/slide.png");
  const int baselineReads = sourceReads;
  const int baselinePaths = pathResolutions;
  for (int frame = 0; frame < 100; ++frame) {
    const auto& scan = nativeTelepromptTrackScan(&project, "TELEPROMPT1");
    assert(scan.items[1].start == 15);
  }
  assert(sourceReads == baselineReads && pathResolutions == baselinePaths);

  // Edit/move, replace take, delete and undo must invalidate before next frame.
  first.start = 80; first.take = &image; ++project.revision;
  const auto& moved = nativeTelepromptTrackScan(&project, "TELEPROMPT1");
  assert(moved.items[0].start == 80 && moved.items[0].take == &image);
  tp.items.erase(tp.items.begin()); ++project.revision;
  assert(nativeTelepromptTrackScan(&project, "TELEPROMPT1").items.size() == 1);
  tp.items.insert(tp.items.begin(), &first); ++project.revision;
  assert(nativeTelepromptTrackScan(&project, "TELEPROMPT1").items.size() == 2);

  // Save As and switching projects with the same revision cannot reuse paths.
  project.directory = "B";
  assert(nativeTelepromptTrackScan(&project, "TELEPROMPT1").items[0].mediaPath == "B/slide.png");
  ReaProject other{project.revision, "C", "Media", {{"TELEPROMPT1", &tp}}};
  assert(nativeTelepromptTrackScan(&other, "TELEPROMPT1").items[0].mediaPath == "C/slide.png");
  assert(nativeTelepromptTrackScan(&project, "CIFRAS").items.empty());
  project.tracks["CIFRAS"] = &tp; ++project.revision;
  assert(nativeTelepromptTrackScan(&project, "CIFRAS").items.size() == 2);

  // External source changes are reconciled even without a project revision.
  image.label = "replacement.png";
  std::this_thread::sleep_for(std::chrono::milliseconds(1050));
  assert(nativeTelepromptTrackScan(&project, "CIFRAS").items[0].mediaPath == "B/replacement.png");
  GetProjectStateChangeCount_ptr = nullptr;
  const int uncachedReads = sourceReads;
  nativeTelepromptTrackScan(&project, "CIFRAS");
  nativeTelepromptTrackScan(&project, "CIFRAS");
  assert(sourceReads == uncachedReads + 4);
  assert(nativeTelepromptTrackScan(nullptr, "TELEPROMPT1").items.empty());
  std::cout << "TELEPROMPT_SCAN_CACHE_OK: edits, take replacement, deletion, undo, projects, paths, expiry; 100 unchanged calls = 0 extra source/path reads\n";
}
